name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:

concurrency:
  group: ios-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ios:
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Print current working directory
        run: pwd

      - name: List directory contents
        run: ls -la

      - name: Print GITHUB_WORKSPACE
        run: echo $GITHUB_WORKSPACE

      - name: Check existence of font directory
        run: |
          if [ -d "../../../../../core/designsystem/src/commonMain/resources/font" ]; then
            echo "Font directory exists"
          else
            echo "Font directory does NOT exist"
          fi

      - name: Find and print relative path to the font directory
        run: |
          found_path=$(find . -type d -name "font" || true)
          if [[ -n "$found_path" ]]; then
            echo "Relative path to font directory: $found_path"
          else
            echo "Font directory not found."
          fi

      - name: Set up Ruby
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 # v1.152.0
        with:
          bundler-cache: true

      - uses: ./.github/actions/xcode-select

      - uses: ./.github/actions/setup-java

      - name: Set up XCFramework arch filter
        run: echo "arch=x86_64" >> local.properties

      - uses: ./.github/actions/spm

      - run: bundle exec fastlane build
        working-directory: app-ios
